name: Publish Release Version NuGet Package

on: 
  push:
    branches: [Release]
    tags:
      - 'v*'
jobs:
  test-build:
    name: Test build on ${{ matrix.os }} .NET 8.0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 8.0
      - uses: actions/checkout@v4
      - name: Restore packages
        run: dotnet restore ProjBobcat/ProjBobcat.sln
      - name: Build Test
        run: dotnet build ProjBobcat/ProjBobcat.sln -c Release --no-restore
  publish-package:
    name: Publish package
    runs-on: windows-latest
    needs: [test-build]
    if: needs.test-build.result == 'success'
    steps:
      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 8.0
      - uses: actions/checkout@v4
      - name: Restore packages
        run: dotnet restore ProjBobcat/ProjBobcat.sln
      - name: Create the package
        run: dotnet pack ProjBobcat/ProjBobcat.sln -c Release
      - name: Publish the package to NuGet.org
        run: dotnet nuget push -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json "ProjBobcat/ProjBobcat/bin/Release/*.nupkg"
